include: "rules/common.smk"


##### Target Rules #####

rule all:
  input:
    "results/bams/fullg/Otsh_v1.0/CH_001.bam"


##### Modules #####


include: "rules/full_genome_map_and_extract.smk"

#include: "rules/beds_and_genomes.smk"
#include: "rules/map_and_extract.smk"
#include: "rules/coverages.smk"
#include: "rules/starts_and_cigars.smk"
#include: "rules/calling.smk"







